name = 'chess'
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[vars]
BYNARA_KEY = "sk-nry-cMvUj1z3NoCVcb7aCSCYZTnnw7rodKaumunu50PjhMA"
RESEMBLE_API_KEY = ""
COOKIE_DOMAIN = ".beeeproject.com"
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "PUZ"
database_name = "puz"
database_id = "9a77b1f0-fce1-4f82-a09f-763676740f8e"


